---
- name: Ensure apt cache is up to date
  apt:
    update_cache: yes
    cache_valid_time: 3600

- name: Install base packages
  apt:
    name: "{{ base_packages }}"
    state: present

- name: Disable swap (required by Kubernetes)
  command: swapoff -a
  when: ansible_swaptotal_mb | int > 0
  changed_when: false

- name: Ensure swap is disabled in fstab
  replace:
    path: /etc/fstab
    regexp: '^(.*\sswap\s.*)$'
    replace: '# \1'

- name: Ensure br_netfilter is enabled
  modprobe:
    name: br_netfilter
    state: present

- name: Configure sysctls for Kubernetes networking
  copy:
    dest: /etc/sysctl.d/99-kubernetes-cri.conf
    content: |
      net.bridge.bridge-nf-call-iptables  = 1
      net.bridge.bridge-nf-call-ip6tables = 1
      net.ipv4.ip_forward                 = 1
  notify: Reload sysctl
