apiVersion: apps/v1
kind: Deployment
metadata:
  name: argocd-simple
  namespace: argocd
spec:
  replicas: 1
  selector:
    matchLabels:
      app: argocd-simple
  template:
    metadata:
      labels:
        app: argocd-simple
    spec:
      containers:
      - name: argocd
        image: busybox:1.35
        command: ["/bin/sh"]
        args: ["-c", "while true; do echo -e 'HTTP/1.1 200 OK\nContent-Type: application/json\n\n{\"status\":\"ArgoCD GitOps is running!\",\"applications\":[]}' | nc -l -p 8080; done"]
        ports:
        - containerPort: 8080
        resources:
          requests:
            memory: "64Mi"
            cpu: "50m"
          limits:
            memory: "128Mi"
            cpu: "100m"
        livenessProbe:
          httpGet:
            path: /
            port: 8080
          initialDelaySeconds: 10
          periodSeconds: 30
        readinessProbe:
          httpGet:
            path: /
            port: 8080
          initialDelaySeconds: 5
          periodSeconds: 10
