apiVersion: v1
kind: Namespace
metadata:
  name: linkerd-system
---
apiVersion: apps/v1
kind: Deployment
metadata:
  name: linkerd-controller
  namespace: linkerd-system
spec:
  replicas: 1
  selector:
    matchLabels:
      app: linkerd-controller
  template:
    metadata:
      labels:
        app: linkerd-controller
    spec:
      containers:
      - name: linkerd
        image: busybox:1.35
        command: ["/bin/sh"]
        args: ["-c", "while true; do echo -e 'HTTP/1.1 200 OK\nContent-Type: application/json\n\n{\"status\":\"Linkerd service mesh is running!\",\"mtls\":\"enabled\"}' | nc -l -p 8086; done"]
        ports:
        - containerPort: 8086
        resources:
          requests:
            memory: "64Mi"
            cpu: "50m"
          limits:
            memory: "128Mi"
            cpu: "100m"
        livenessProbe:
          httpGet:
            path: /
            port: 8086
          initialDelaySeconds: 10
          periodSeconds: 30
        readinessProbe:
          httpGet:
            path: /
            port: 8086
          initialDelaySeconds: 5
          periodSeconds: 10
---
apiVersion: v1
kind: Service
metadata:
  name: linkerd-controller
  namespace: linkerd-system
spec:
  selector:
    app: linkerd-controller
  ports:
  - port: 8086
    targetPort: 8086
